import type { MetadataRoute } from "next";

const BASE_URL = "https://www.augle.com";

const ROUTES = [
  "/",
  "/about",
  "/blog",
  "/careers",
  "/contact",
  "/deliberation-index",
  "/deliberation-index/explorer",
  "/deliberation-index/heatmap",
  "/deliberation-index/methodology",
  "/download",
  "/glossary",
  "/how-it-works",
  "/how-it-works/agents",
  "/how-it-works/guardian",
  "/how-it-works/phases",
  "/how-it-works/scoring",
  "/outcomes",
  "/outcomes/browser",
  "/outcomes/macro-cpi-print",
  "/outcomes/life-crispr-reproducibility",
  "/outcomes/life-glp1-vs-bariatric",
  "/outcomes/edu-dissertation-defence",
  "/outcomes/policy-masking-mandates",
  "/outcomes/policy-mnpi-exposure",
  "/outcomes/tech-photonic-chip",
  "/outcomes/rag-hallucination-reduction",
  "/outcomes/soc-screen-time-depression",
  "/press",
  "/pricing",
  "/privacy",
  "/release-notes",
  "/research",
  "/security",
  "/solutions",
  "/solutions/enterprise",
  "/solutions/healthcare",
  "/solutions/universities",
  "/solutions/financial-services",
  "/solutions/government",
  "/solutions/law-firms",
  "/solutions/media",
  "/solutions/policy",
  "/solutions/research-labs",
  "/solutions/think-tanks",
  "/solutions/venture-capital",
  "/terms",
  "/use-cases",
  "/use-cases/universities",
  "/use-cases/research-labs",
  "/use-cases/policy",
  "/use-cases/law-firms",
  "/use-cases/venture-capital",
  "/use-cases/think-tanks",
  "/use-cases/enterprise",
  "/use-cases/healthcare",
  "/use-cases/government",
  "/use-cases/financial-services",
  "/use-cases/media",
  "/waitlist",
];

export default function sitemap(): MetadataRoute.Sitemap {
  return ROUTES.map((path) => ({
    url: `${BASE_URL}${path}`,
    lastModified: new Date(),
  }));
}
