import type { Metadata } from "next";
import { LegalLayout, legalH2, legalLi, legalLink, legalP, legalUl } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — Augle",
  description: "Augle's Terms of Service — the terms governing use of our website and platform.",
};

const TOC = [
  { id: "acceptance", label: "Acceptance of terms" },
  { id: "description", label: "Description of the Service" },
  { id: "changesservice", label: "Changes to the Service" },
  { id: "eligibility", label: "Eligibility" },
  { id: "accounts", label: "Accounts" },
  { id: "credits", label: "Credits and payment" },
  { id: "use", label: "Acceptable use" },
  { id: "content", label: "Your content and Findings" },
  { id: "feedback", label: "Feedback" },
  { id: "ip", label: "Intellectual property" },
  { id: "dmca", label: "Copyright complaints (DMCA)" },
  { id: "thirdparty", label: "Third-party services" },
  { id: "disclaimer", label: "Findings are not professional advice" },
  { id: "warranty", label: "Warranty disclaimer" },
  { id: "liability", label: "Limitation of liability" },
  { id: "indemnity", label: "Indemnification" },
  { id: "termination", label: "Termination" },
  { id: "dispute", label: "Dispute resolution" },
  { id: "law", label: "Governing law" },
  { id: "forcemajeure", label: "Force majeure" },
  { id: "export", label: "Export control" },
  { id: "general", label: "General provisions" },
  { id: "changes", label: "Changes to these terms" },
  { id: "contact", label: "Contact us" },
];

export default function TermsPage() {
  return (
    <LegalLayout crumbLabel="Terms of Service" title="Terms of Service" lastUpdated="Last updated: [Month] 2026" toc={TOC}>
      <h2 id="acceptance" className={legalH2}>1. Acceptance of terms</h2>
      <p className={legalP}>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of Augle, Inc.&apos;s
        (&quot;Augle,&quot; &quot;we,&quot; &quot;us&quot;) website and multi-agent deliberation
        platform (the &quot;Service&quot;). By creating an account or otherwise using the Service, you
        agree to be bound by these Terms. If you do not agree, do not use the Service.
      </p>

      <h2 id="description" className={legalH2}>2. Description of the Service</h2>
      <p className={legalP}>
        Augle operates a multi-agent AI deliberation platform. You submit a research question and,
        optionally, supporting documents or URLs; a multi-agent ensemble examines the question across
        structured phases and produces a Finding with a calibrated confidence grade (Established,
        Probable, Contested, or Gap). Findings are generated by an automated system and reflect the
        evidence available at the time of the session.
      </p>

      <h2 id="changesservice" className={legalH2}>3. Changes to the Service</h2>
      <p className={legalP}>
        We may add, modify, or discontinue features of the Service at any time. We will use
        reasonable efforts to provide notice of material changes that affect your ability to use
        previously purchased credits.
      </p>

      <h2 id="eligibility" className={legalH2}>4. Eligibility</h2>
      <p className={legalP}>
        You must be at least 18 years old, or the age of majority in your jurisdiction, and capable
        of forming a binding contract to use the Service. If you use the Service on behalf of an
        organization, you represent that you have authority to bind that organization to these Terms,
        and &quot;you&quot; refers to both you and that organization.
      </p>

      <h2 id="accounts" className={legalH2}>5. Accounts</h2>
      <p className={legalP}>
        You are responsible for maintaining the confidentiality of your account credentials and for
        all activity under your account. Notify us immediately of any unauthorized use. We are not
        liable for any loss arising from unauthorized use of your account that occurs before you
        notify us.
      </p>

      <h2 id="credits" className={legalH2}>6. Credits and payment</h2>
      <p className={legalP}>
        Access to deliberation sessions is provided on a credit basis. Credits are purchased in
        advance, do not expire, and are non-refundable except where required by law or expressly
        stated otherwise. Session pricing varies by depth tier. New accounts receive one complimentary
        Standard session. You are responsible for all applicable taxes; prices are exclusive of tax
        unless stated otherwise.
      </p>

      <h2 id="use" className={legalH2}>7. Acceptable use</h2>
      <p className={legalP}>You agree not to:</p>
      <ul className={legalUl}>
        <li className={legalLi}>Use the Service for any unlawful purpose or to violate any applicable law or regulation.</li>
        <li className={legalLi}>
          Submit content you do not have the right to share, or that infringes third-party
          intellectual property or privacy rights.
        </li>
        <li className={legalLi}>
          Attempt to reverse-engineer, decompile, scrape at scale, or interfere with the Service&apos;s
          underlying systems or security.
        </li>
        <li className={legalLi}>
          Use the Service to generate content intended to harass, deceive, defame, or harm others.
        </li>
        <li className={legalLi}>Misrepresent a Finding&apos;s confidence grade or provenance when sharing it externally.</li>
        <li className={legalLi}>Use the Service to build a competing product, or to train a competing AI model.</li>
        <li className={legalLi}>Circumvent any usage limits, credit metering, or access controls.</li>
        <li className={legalLi}>Introduce malware or attempt to gain unauthorized access to any part of the Service.</li>
      </ul>
      <p className={legalP}>
        We reserve the right to investigate suspected violations and to suspend or terminate access
        for any violation of this section.
      </p>

      <h2 id="content" className={legalH2}>8. Your content and Findings</h2>
      <p className={legalP}>
        You retain ownership of documents and questions you submit (&quot;Your Content&quot;). By
        submitting Your Content, you grant Augle a limited, worldwide, non-exclusive license to host,
        process, and analyze it for the purpose of running your session and generating a Finding,
        and, in de-identified or aggregate form, to improve calibration and Service quality. You
        represent that you have the necessary rights to submit Your Content and to grant this
        license.
      </p>
      <p className={legalP}>
        Subject to these Terms and any applicable credit or subscription terms, you may use, share,
        and publish the Findings generated from your own sessions. Augle makes no representation that
        a Finding is complete, error-free, or suitable for any particular purpose.
      </p>

      <h2 id="feedback" className={legalH2}>9. Feedback</h2>
      <p className={legalP}>
        If you provide feedback or suggestions about the Service, you grant Augle the right to use
        that feedback without restriction or compensation to you.
      </p>

      <h2 id="ip" className={legalH2}>10. Intellectual property</h2>
      <p className={legalP}>
        The Service, including its underlying architecture, agent design, calibration methodology,
        software, and all associated patents, trademarks, and content (excluding Your Content), is
        the property of Augle, Inc. and its licensors and is protected by intellectual property laws.
        These Terms do not grant you any rights to Augle&apos;s intellectual property except a
        limited, revocable, non-transferable license to use the Service as intended.
      </p>

      <h2 id="dmca" className={legalH2}>11. Copyright complaints (DMCA)</h2>
      <p className={legalP}>
        If you believe content accessible through the Service infringes your copyright, you may
        submit a notice to <a href="mailto:legal@augle.com" className={legalLink}>legal@augle.com</a>{" "}
        including the information required under the Digital Millennium Copyright Act (identification
        of the copyrighted work, the allegedly infringing material, your contact information, and a
        statement of good-faith belief and accuracy under penalty of perjury).{" "}
        <em>[A formal designated-agent registration will be completed prior to launch.]</em>
      </p>

      <h2 id="thirdparty" className={legalH2}>12. Third-party services</h2>
      <p className={legalP}>
        The Service relies on third-party infrastructure and AI model providers to operate. We are
        not responsible for the availability, accuracy, or performance of third-party services,
        though we select and monitor providers with reasonable care.
      </p>

      <h2 id="disclaimer" className={legalH2}>13. Findings are not professional advice</h2>
      <p className={legalP}>
        Findings produced by the Service are informational and reflect an automated assessment of
        available evidence at a point in time. They are <strong className="text-ink">not</strong>{" "}
        legal, medical, financial, or other professional advice, and should not be relied upon as a
        substitute for consultation with a qualified professional. You are solely responsible for
        decisions made based on a Finding, and for independently verifying any Finding before relying
        on it in a high-stakes context.
      </p>

      <h2 id="warranty" className={legalH2}>14. Warranty disclaimer</h2>
      <p className={legalP}>
        The Service is provided &quot;as is&quot; and &quot;as available,&quot; without warranties of
        any kind, express or implied, including implied warranties of merchantability, fitness for a
        particular purpose, title, and non-infringement. We do not warrant that the Service will be
        uninterrupted, secure, or error-free, or that any Finding will be accurate or complete.
      </p>

      <h2 id="liability" className={legalH2}>15. Limitation of liability</h2>
      <p className={legalP}>
        To the maximum extent permitted by law, Augle and its officers, directors, employees, and
        licensors will not be liable for any indirect, incidental, special, consequential, exemplary,
        or punitive damages, or any loss of profits, revenue, data, or goodwill, arising from your use
        of the Service, even if advised of the possibility of such damages. Our total aggregate
        liability for any claim arising from these Terms or the Service will not exceed the greater
        of (a) the amount you paid to Augle in the twelve months preceding the claim, or (b) one
        hundred U.S. dollars ($100). Some jurisdictions do not allow the exclusion or limitation of
        certain damages, so some of the above limitations may not apply to you.
      </p>

      <h2 id="indemnity" className={legalH2}>16. Indemnification</h2>
      <p className={legalP}>
        You agree to indemnify and hold harmless Augle and its officers, directors, employees, and
        licensors from any claims, damages, liabilities, and expenses (including reasonable
        attorneys&apos; fees) arising from: (a) Your Content; (b) your use of the Service in violation
        of these Terms; or (c) your violation of any law or third-party right.
      </p>

      <h2 id="termination" className={legalH2}>17. Termination</h2>
      <p className={legalP}>
        We may suspend or terminate your access to the Service if you violate these Terms, if
        required by law, or if we discontinue the Service, with notice where reasonably practicable.
        You may stop using the Service and close your account at any time. Upon termination, your
        right to use the Service ceases immediately; unused credits are handled as described in
        Section 6 and applicable law. Sections that by their nature should survive termination
        (including Sections 9–16 and 18–22) will survive.
      </p>

      <h2 id="dispute" className={legalH2}>18. Dispute resolution</h2>
      <p className={legalP}>
        <em>
          [This section will set out the process for resolving disputes — for example, an agreement
          to attempt informal resolution first, followed by binding arbitration and/or a class-action
          waiver, or alternatively a straightforward right to litigate in a specified venue. This is a
          meaningful business decision (arbitration vs. litigation, class waiver or not) that should
          be made with counsel before publication, rather than defaulted by template.]
        </em>
      </p>

      <h2 id="law" className={legalH2}>19. Governing law</h2>
      <p className={legalP}>
        These Terms are governed by the laws of the State of Delaware, without regard to
        conflict-of-law principles. <em>[Venue provisions to be finalized alongside Section 18 with counsel prior to publication.]</em>
      </p>

      <h2 id="forcemajeure" className={legalH2}>20. Force majeure</h2>
      <p className={legalP}>
        Augle will not be liable for any failure or delay in performance resulting from causes beyond
        our reasonable control, including acts of God, natural disaster, war, terrorism, labor
        disputes, internet or utility failures, or failures of third-party service providers.
      </p>

      <h2 id="export" className={legalH2}>21. Export control</h2>
      <p className={legalP}>
        You may not use or export the Service in violation of U.S. export laws and regulations, and
        you represent that you are not located in, or a national or resident of, any country subject
        to U.S. government embargo, and are not on any U.S. government restricted-party list.
      </p>

      <h2 id="general" className={legalH2}>22. General provisions</h2>
      <p className={legalP}>
        <strong className="text-ink">Assignment.</strong> You may not assign these Terms without our
        consent; we may assign these Terms in connection with a merger, acquisition, or sale of
        assets.
      </p>
      <p className={legalP}>
        <strong className="text-ink">Severability.</strong> If any provision of these Terms is found
        unenforceable, the remaining provisions will remain in full effect.
      </p>
      <p className={legalP}>
        <strong className="text-ink">No waiver.</strong> Our failure to enforce any right or provision
        will not be considered a waiver of that right or provision.
      </p>
      <p className={legalP}>
        <strong className="text-ink">Entire agreement.</strong> These Terms, together with our
        Privacy Policy and any order forms or agreements referencing them, constitute the entire
        agreement between you and Augle regarding the Service.
      </p>
      <p className={legalP}>
        <strong className="text-ink">Notices.</strong> We may provide notices to you via the email
        associated with your account or through the Service. You may send notices to us at the
        contact address below.
      </p>

      <h2 id="changes" className={legalH2}>23. Changes to these terms</h2>
      <p className={legalP}>
        We may update these Terms from time to time. We will post the updated version here with a
        revised &quot;Last updated&quot; date, and where changes are material, we will provide
        additional notice. Continued use of the Service after changes take effect constitutes
        acceptance of the revised Terms.
      </p>

      <h2 id="contact" className={legalH2}>24. Contact us</h2>
      <p className={legalP}>
        Questions about these Terms can be directed to{" "}
        <a href="mailto:legal@augle.com" className={legalLink}>legal@augle.com</a>.
      </p>
    </LegalLayout>
  );
}
